### ISSUE TITLE
Trabajo por hacer

### ISSUE THREAD

**Issue by asanzo** [alejandroFerrante/Woblocks#7]
Por ahora cargo esto así, pero idealmente deberíamos tener un project.
Lo cargo acá pero después hablamos en la reunión mejor de esto.

**No se saltea nada, se hace en orden**

- [x] Hacer un project y cargar todas estas cosas como issues
- [x] Agregar un README con la forma de tener el proyecto andando. Como [este](https://github.com/uqbar-project/wollok-ts-cli/blob/master/README.md) #8
- [x] Poder apretar stop y play y volver a jugar el juego sin recargar imágenes. Para esto con poner las imágenes dentro de un directorio alcanzable ya deberíamos estar. Que sea la galería (oculta por ahora) de imágenes disponibles. #9
- [x] Issue #3 
- [x] Presentar plan de tesis #10
- [x] Diseñar en papel la vista de la aplicación. Esto lo hacemos en un meet todos juntos. O presencial en pizarrón, whatever. #11
- [x] Elegir framework e implementar el diseño. Usando librerías existentes como la de Material Design para no tener que elegir fonts/colores/formas, etc. Aprovechar esta implementación para refactorizar. Probablemente necesitemos tener "momento de build". #12
- [x] Probar interfaz con usuaries que no seamos nosotros. #13
- [x] Escribir tesis #14
- [ ] Recibirme
- [x] Stop rompe todo. Esto no lo podemos arreglar hasta que en Wollok Game no resuelvan [este issue](https://github.com/uqbar-project/wollok-game-web/issues/1) #15

**Comment by asanzo** [comment]
Cierro porque ya cargué los issues en el project: https://github.com/alejandroFerrante/Woblocks/projects/1?fullscreen=true
